ДЗ 1
SchokoladeDasha/2020-1-Atom-QA-Python-D-Mashtak pull request #1
Opened 2020-03-04 20:49 UTC by SchokoladeDasha

# Домашнее задание № 1

Прошу @snicks92 или @z1ll1 проверить его.

Что было сделано:
* Написаны тесты для 5 структур данных Python
* Добавлен файл Requirements.txt

2020-03-12 13:09 UTC, sniiick requested changes
Все хорошо, несколько мелких замечаний

2020-03-12 13:09 UTC, snicks92 commented on Homework1/test_dictionary.py
> +    assert eval(s) == val
eval не самая лучшая идея, лучше через getattr
```python
>>> method = getattr({1: 2, 3: 4}, 'values')
>>> method
<built-in method values of dict object at 0x101cefa40>
>>> list(method())
[2, 4]
```

2020-03-12 13:09 UTC, snicks92 commented on Homework1/test_int.py
> +    assert eval(a) == value
То же самое, вместо этого можно воспользоваться __magic__ методами, вот пример для сложения:

```python
>>> var = 1
>>> var.__add__(2)
3
```

Сам метод можно так же получить через getattr

2020-03-12 13:09 UTC, snicks92 commented on Pipfile
> +[[source]]
Лишнее, договорились, что кладем только requirements.txt.
Pipfile.lock аналогично

2020-03-14 21:14 UTC, sniiick approved these changes

2020-03-14 21:14 UTC, merged

2020-03-14 21:14 UTC, snicks92 commented
Отлично, спасибо